### ISSUE TITLE
No way of sourcing with use-package

### ISSUE THREAD

**Issue by ghost** [mihaiolteanu/lastfm.el#3]
There's no way of sourcing this package with any use-package declaration. Please support packaging standards as seen in any of alphapapa's packages.

`(use-package lastfm :demand t :straight (:host github :repo "mihaiolteanu/lastfm"))` exposes no usable commands.

Additional packages are required for your package which are no where explained in the README. I needed, 
```
  (use-package anaphora)
  (use-package elquery)
  (use-package lastfm :demand t :straight (:host github :repo "mihaiolteanu/lastfm"))
```
just to get to a place where I could make this issue.

If I want to use Vuiet I need, additionally,
```
  (use-package versuri :demand t :straight (:host github :repo "mihaiolteanu/versuri"))
  (use-package vuiet :demand t :straight (:host github :repo "mihaiolteanu/vuiet"))
```

This is a lot of steps to a usable environment. The link given in the readme to https://www.last.fm/api/ doesn't work. This is many broken things.

**Comment by mihaiolteanu** [comment]
> Please support packaging standards

Both packages can be installed directly from melpa.
PR's are welcome to improve things.

> The link given in the readme to https://www.last.fm/api/ doesn't work.

That's the official last.fm api page. If it doesn't work, I'm surely not to blame.

> This is many broken things.

As always with free software, you have the option of not using it.

**Comment by ghost** [comment]
@mihaiolteanu hey man, you posted Vuiet on Hacker News, which is typically an invite for constructive criticism. I'm not telling you your package sucks. I'm telling you it needs work and I'm telling you where it needs work.

I'm not a package developer. My work is backend. You're more than welcome to tell me my criticism is not welcome but let's not turn this into you being defensive.

**Comment by mihaiolteanu** [comment]
Matthew, thank you for your time and effort.
