### ISSUE TITLE
Cannot perform requests

### ISSUE THREAD

**Issue by shevchuk** [mihaiolteanu/lastfm.el#5]
Thanks for building this module and vuiet, I am trying to set it up working. I followed the procedure to add credentials and looks like I have some valid .lastfmrc but when I ran any command I get:

```Debugger entered--Lisp error: (wrong-type-argument sequencep 10)
  mapconcat(#f(compiled-function (byte) #<bytecode 0x1a2df2d>) 10 "")
  url-hexify-string(10)
  request--urlencode-alist((("api_key" . "{removed}") ("method" . "artist.search") ("artist" . "stereophonics") ("limit" . 10)))
  request("http://ws.audioscrobbler.com/2.0/" :params (("api_key" . "{removed}") ("method" . "artist.search") ("artist" . "stereophonics") ("limit" . 10)) :parser buffer-string :type "POST" :sync t :complete #f(compiled-function (&rest rest) #<bytecode 0x1a89a81>))
  lastfm--request("artist.search" :no (artist limit) "stereophonics" 10)
  lastfm-artist-search("stereophonics")
  eval((lastfm-artist-search "stereophonics") nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

Any ideas why it failed?

**Comment by mihaiolteanu** [comment]
Hello Mike,

I don't see any errors in there. Why would you say it failed?
Or is this the only output you got after eval-ing the `(lastfm-artist-search "stereophonics")` form?

Also, do any of the other calls work, like, `(lastfm-artist-top-tracks "stereophonics")`, for example? (edit: you've said 'but when I ran any command', so forget this question)

I would say the issue could be the wrong api-key, but if that's the case, you would get a nice error telling you exactly that.

I'm waiting on your response.

**Comment by mihaiolteanu** [comment]
You can also [check](https://www.last.fm/settings/applications) your last.fm account and see if you have anything in your "Connected Applications" entry. 

Also, check your `~/.lastfmrc` file and make sure you have at least your API-KEY,  SHARED-SECRET and USERNAME filled up.

**Comment by shevchuk** [comment]
Thanks for your double-quick answer, I guess I've just realized what was the issue:
It was an old version of 'request' - it was 0.2.0 instead of 0.3.x
I've upgraded that and now it looks good!
